server:
  port: 8761

eureka:
  instance:
    hostname: eureka8761.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka8762.com:8762/eureka/
