server:
  port: 8762

eureka:
  instance:
#    hostname: cloud-demo-eureka-8762
    hostname: eureka8762.com
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka8761.com:8761/eureka/

spring:
  application:
    name: Eureka-Cluster
